# Generated by Django 5.0.4 on 2024-04-07 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_customer_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="billing.employee",
            ),
        ),
    ]
