# Generated by Django 5.0.4 on 2024-04-08 21:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0003_bill_employee"),
    ]

    operations = []
